RunId: HD_402d014f-07d3-4c64-b158-86d3d0890819
Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819?wsid=/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourcegroups/aml-quickstarts-122756/workspaces/quick-starts-ws-122756

Streaming azureml-logs/hyperdrive.txt
=====================================

"<START>[2020-10-25T05:18:02.712826][API][INFO]Experiment created<END>\n""<START>[2020-10-25T05:18:03.791644][GENERATOR][INFO]Trying to sample '5' jobs from the hyperparameter space<END>\n""<START>[2020-10-25T05:18:04.279677][GENERATOR][INFO]Successfully sampled '5' jobs, they will soon be submitted to the execution target.<END>\n"<START>[2020-10-25T05:18:05.0309346Z][SCHEDULER][INFO]The execution environment is being prepared. Please be patient as it can take a few minutes.<END>

Execution Summary
=================
RunId: HD_402d014f-07d3-4c64-b158-86d3d0890819
Web View: https://ml.azure.com/experiments/udacity-project/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819?wsid=/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourcegroups/aml-quickstarts-122756/workspaces/quick-starts-ws-122756

Warnings:
{
  "error": {
    "code": "UserError",
    "severity": null,
    "message": "User errors were found in at least one of the child runs.",
    "messageFormat": null,
    "messageParameters": {},
    "referenceCode": null,
    "detailsUri": null,
    "target": null,
    "details": [],
    "innerError": null,
    "debugInfo": {
      "type": null,
      "message": "[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {'error': {\n    \"additional_properties\": {\n        \"componentName\": null\n    },\n    \"error\": {\n        \"additional_properties\": {\n            \"referenceCode\": null,\n            \"messageFormat\": null,\n            \"severity\": null,\n            \"messageParameters\": {}\n        },\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with SystemExit: 2\",\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\n        \"target\": null,\n        \"details\": [],\n        \"inner_error\": null,\n        \"debug_info\": {\n            \"additional_properties\": {},\n            \"type\": \"SystemExit\",\n            \"message\": \"2\",\n            \"stack_trace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 81, in <module>\\n    main()\\n  File \\\"train.py\\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 1733, in parse_args\\n    self.error(msg % ' '.join(argv))\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2389, in error\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\n') % args)\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2376, in exit\\n    _sys.exit(status)\\n\",\n            \"inner_exception\": null,\n            \"data\": null,\n            \"error_response\": null\n        }\n    },\n    \"correlation\": null,\n    \"environment\": null,\n    \"location\": null,\n    \"time\": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {'error': {\n    \"additional_properties\": {\n        \"componentName\": null\n    },\n    \"error\": {\n        \"additional_properties\": {\n            \"referenceCode\": null,\n            \"messageFormat\": null,\n            \"severity\": null,\n            \"messageParameters\": {}\n        },\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with SystemExit: 2\",\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\n        \"target\": null,\n        \"details\": [],\n        \"inner_error\": null,\n        \"debug_info\": {\n            \"additional_properties\": {},\n            \"type\": \"SystemExit\",\n            \"message\": \"2\",\n            \"stack_trace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 81, in <module>\\n    main()\\n  File \\\"train.py\\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 1733, in parse_args\\n    self.error(msg % ' '.join(argv))\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2389, in error\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\n') % args)\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2376, in exit\\n    _sys.exit(status)\\n\",\n            \"inner_exception\": null,\n            \"data\": null,\n            \"error_response\": null\n        }\n    },\n    \"correlation\": null,\n    \"environment\": null,\n    \"location\": null,\n    \"time\": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {'error': {\n    \"additional_properties\": {\n        \"componentName\": null\n    },\n    \"error\": {\n        \"additional_properties\": {\n            \"referenceCode\": null,\n            \"messageFormat\": null,\n            \"severity\": null,\n            \"messageParameters\": {}\n        },\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with SystemExit: 2\",\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\n        \"target\": null,\n        \"details\": [],\n        \"inner_error\": null,\n        \"debug_info\": {\n            \"additional_properties\": {},\n            \"type\": \"SystemExit\",\n            \"message\": \"2\",\n            \"stack_trace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 81, in <module>\\n    main()\\n  File \\\"train.py\\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 1733, in parse_args\\n    self.error(msg % ' '.join(argv))\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2389, in error\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\n') % args)\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2376, in exit\\n    _sys.exit(status)\\n\",\n            \"inner_exception\": null,\n            \"data\": null,\n            \"error_response\": null\n        }\n    },\n    \"correlation\": null,\n    \"environment\": null,\n    \"location\": null,\n    \"time\": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {'error': {\n    \"additional_properties\": {\n        \"componentName\": null\n    },\n    \"error\": {\n        \"additional_properties\": {\n            \"referenceCode\": null,\n            \"messageFormat\": null,\n            \"severity\": null,\n            \"messageParameters\": {}\n        },\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with SystemExit: 2\",\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\n        \"target\": null,\n        \"details\": [],\n        \"inner_error\": null,\n        \"debug_info\": {\n            \"additional_properties\": {},\n            \"type\": \"SystemExit\",\n            \"message\": \"2\",\n            \"stack_trace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 81, in <module>\\n    main()\\n  File \\\"train.py\\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 1733, in parse_args\\n    self.error(msg % ' '.join(argv))\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2389, in error\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\n') % args)\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2376, in exit\\n    _sys.exit(status)\\n\",\n            \"inner_exception\": null,\n            \"data\": null,\n            \"error_response\": null\n        }\n    },\n    \"correlation\": null,\n    \"environment\": null,\n    \"location\": null,\n    \"time\": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {'error': {\n    \"additional_properties\": {\n        \"componentName\": null\n    },\n    \"error\": {\n        \"additional_properties\": {\n            \"referenceCode\": null,\n            \"messageFormat\": null,\n            \"severity\": null,\n            \"messageParameters\": {}\n        },\n        \"code\": \"UserError\",\n        \"message\": \"User program failed with SystemExit: 2\",\n        \"details_uri\": \"https://aka.ms/azureml-known-errors\",\n        \"target\": null,\n        \"details\": [],\n        \"inner_error\": null,\n        \"debug_info\": {\n            \"additional_properties\": {},\n            \"type\": \"SystemExit\",\n            \"message\": \"2\",\n            \"stack_trace\": \"  File \\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\"__main__\\\")\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\\"/opt/miniconda/lib/python3.6/runpy.py\\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\\"train.py\\\", line 81, in <module>\\n    main()\\n  File \\\"train.py\\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 1733, in parse_args\\n    self.error(msg % ' '.join(argv))\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2389, in error\\n    self.exit(2, _('%(prog)s: error: %(message)s\\\\n') % args)\\n  File \\\"/opt/miniconda/lib/python3.6/argparse.py\\\", line 2376, in exit\\n    _sys.exit(status)\\n\",\n            \"inner_exception\": null,\n            \"data\": null,\n            \"error_response\": null\n        }\n    },\n    \"correlation\": null,\n    \"environment\": null,\n    \"location\": null,\n    \"time\": {}\n}})]",
      "stackTrace": null,
      "innerException": null,
      "data": null,
      "errorResponse": null
    }
  },
  "correlation": null,
  "environment": null,
  "location": null,
  "time": "0001-01-01T00:00:00+00:00",
  "componentName": null
}


{'runId': 'HD_402d014f-07d3-4c64-b158-86d3d0890819',
 'target': 'opt-ml-cluster',
 'status': 'Canceled',
 'startTimeUtc': '2020-10-25T05:18:01.922729Z',
 'endTimeUtc': '2020-10-25T05:22:35.704274Z',
 'error': {'error': {'code': 'UserError',
   'message': 'User errors were found in at least one of the child runs.',
   'details': [],
   'debugInfo': {'message': '[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {\'error\': {\n    "additional_properties": {\n        "componentName": null\n    },\n    "error": {\n        "additional_properties": {\n            "referenceCode": null,\n            "messageFormat": null,\n            "severity": null,\n            "messageParameters": {}\n        },\n        "code": "UserError",\n        "message": "User program failed with SystemExit: 2",\n        "details_uri": "https://aka.ms/azureml-known-errors",\n        "target": null,\n        "details": [],\n        "inner_error": null,\n        "debug_info": {\n            "additional_properties": {},\n            "type": "SystemExit",\n            "message": "2",\n            "stack_trace": "  File \\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\"__main__\\")\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"train.py\\", line 81, in <module>\\n    main()\\n  File \\"train.py\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 1733, in parse_args\\n    self.error(msg % \' \'.join(argv))\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2389, in error\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\n\') % args)\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2376, in exit\\n    _sys.exit(status)\\n",\n            "inner_exception": null,\n            "data": null,\n            "error_response": null\n        }\n    },\n    "correlation": null,\n    "environment": null,\n    "location": null,\n    "time": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {\'error\': {\n    "additional_properties": {\n        "componentName": null\n    },\n    "error": {\n        "additional_properties": {\n            "referenceCode": null,\n            "messageFormat": null,\n            "severity": null,\n            "messageParameters": {}\n        },\n        "code": "UserError",\n        "message": "User program failed with SystemExit: 2",\n        "details_uri": "https://aka.ms/azureml-known-errors",\n        "target": null,\n        "details": [],\n        "inner_error": null,\n        "debug_info": {\n            "additional_properties": {},\n            "type": "SystemExit",\n            "message": "2",\n            "stack_trace": "  File \\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\"__main__\\")\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"train.py\\", line 81, in <module>\\n    main()\\n  File \\"train.py\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 1733, in parse_args\\n    self.error(msg % \' \'.join(argv))\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2389, in error\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\n\') % args)\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2376, in exit\\n    _sys.exit(status)\\n",\n            "inner_exception": null,\n            "data": null,\n            "error_response": null\n        }\n    },\n    "correlation": null,\n    "environment": null,\n    "location": null,\n    "time": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {\'error\': {\n    "additional_properties": {\n        "componentName": null\n    },\n    "error": {\n        "additional_properties": {\n            "referenceCode": null,\n            "messageFormat": null,\n            "severity": null,\n            "messageParameters": {}\n        },\n        "code": "UserError",\n        "message": "User program failed with SystemExit: 2",\n        "details_uri": "https://aka.ms/azureml-known-errors",\n        "target": null,\n        "details": [],\n        "inner_error": null,\n        "debug_info": {\n            "additional_properties": {},\n            "type": "SystemExit",\n            "message": "2",\n            "stack_trace": "  File \\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\"__main__\\")\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"train.py\\", line 81, in <module>\\n    main()\\n  File \\"train.py\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 1733, in parse_args\\n    self.error(msg % \' \'.join(argv))\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2389, in error\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\n\') % args)\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2376, in exit\\n    _sys.exit(status)\\n",\n            "inner_exception": null,\n            "data": null,\n            "error_response": null\n        }\n    },\n    "correlation": null,\n    "environment": null,\n    "location": null,\n    "time": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {\'error\': {\n    "additional_properties": {\n        "componentName": null\n    },\n    "error": {\n        "additional_properties": {\n            "referenceCode": null,\n            "messageFormat": null,\n            "severity": null,\n            "messageParameters": {}\n        },\n        "code": "UserError",\n        "message": "User program failed with SystemExit: 2",\n        "details_uri": "https://aka.ms/azureml-known-errors",\n        "target": null,\n        "details": [],\n        "inner_error": null,\n        "debug_info": {\n            "additional_properties": {},\n            "type": "SystemExit",\n            "message": "2",\n            "stack_trace": "  File \\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\"__main__\\")\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"train.py\\", line 81, in <module>\\n    main()\\n  File \\"train.py\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 1733, in parse_args\\n    self.error(msg % \' \'.join(argv))\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2389, in error\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\n\') % args)\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2376, in exit\\n    _sys.exit(status)\\n",\n            "inner_exception": null,\n            "data": null,\n            "error_response": null\n        }\n    },\n    "correlation": null,\n    "environment": null,\n    "location": null,\n    "time": {}\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {\'error\': {\n    "additional_properties": {\n        "componentName": null\n    },\n    "error": {\n        "additional_properties": {\n            "referenceCode": null,\n            "messageFormat": null,\n            "severity": null,\n            "messageParameters": {}\n        },\n        "code": "UserError",\n        "message": "User program failed with SystemExit: 2",\n        "details_uri": "https://aka.ms/azureml-known-errors",\n        "target": null,\n        "details": [],\n        "inner_error": null,\n        "debug_info": {\n            "additional_properties": {},\n            "type": "SystemExit",\n            "message": "2",\n            "stack_trace": "  File \\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\", line 181, in execute_with_context\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\"__main__\\")\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 263, in run_path\\n    pkg_name=pkg_name, script_name=fname)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 96, in _run_module_code\\n    mod_name, mod_spec, pkg_name, script_name)\\n  File \\"/opt/miniconda/lib/python3.6/runpy.py\\", line 85, in _run_code\\n    exec(code, run_globals)\\n  File \\"train.py\\", line 81, in <module>\\n    main()\\n  File \\"train.py\\", line 67, in main\\n    args = parser.parse_args()\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 1733, in parse_args\\n    self.error(msg % \' \'.join(argv))\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2389, in error\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\n\') % args)\\n  File \\"/opt/miniconda/lib/python3.6/argparse.py\\", line 2376, in exit\\n    _sys.exit(status)\\n",\n            "inner_exception": null,\n            "data": null,\n            "error_response": null\n        }\n    },\n    "correlation": null,\n    "environment": null,\n    "location": null,\n    "time": {}\n}})]'},
   'messageParameters': {}},
  'time': '0001-01-01T00:00:00.000Z'},
 'warnings': [{'source': 'SecondaryError',
   'message': '{\n  "error": {\n    "code": "UserError",\n    "severity": null,\n    "message": "User errors were found in at least one of the child runs.",\n    "messageFormat": null,\n    "messageParameters": {},\n    "referenceCode": null,\n    "detailsUri": null,\n    "target": null,\n    "details": [],\n    "innerError": null,\n    "debugInfo": {\n      "type": null,\n      "message": "[(https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_0, {\'error\': {\\n    \\"additional_properties\\": {\\n        \\"componentName\\": null\\n    },\\n    \\"error\\": {\\n        \\"additional_properties\\": {\\n            \\"referenceCode\\": null,\\n            \\"messageFormat\\": null,\\n            \\"severity\\": null,\\n            \\"messageParameters\\": {}\\n        },\\n        \\"code\\": \\"UserError\\",\\n        \\"message\\": \\"User program failed with SystemExit: 2\\",\\n        \\"details_uri\\": \\"https://aka.ms/azureml-known-errors\\",\\n        \\"target\\": null,\\n        \\"details\\": [],\\n        \\"inner_error\\": null,\\n        \\"debug_info\\": {\\n            \\"additional_properties\\": {},\\n            \\"type\\": \\"SystemExit\\",\\n            \\"message\\": \\"2\\",\\n            \\"stack_trace\\": \\"  File \\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_0/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_0/azureml-setup/context_manager_injector.py\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\"__main__\\\\\\")\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\"train.py\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\"train.py\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \' \'.join(argv))\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2389, in error\\\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\\\\\n\') % args)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\",\\n            \\"inner_exception\\": null,\\n            \\"data\\": null,\\n            \\"error_response\\": null\\n        }\\n    },\\n    \\"correlation\\": null,\\n    \\"environment\\": null,\\n    \\"location\\": null,\\n    \\"time\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_1, {\'error\': {\\n    \\"additional_properties\\": {\\n        \\"componentName\\": null\\n    },\\n    \\"error\\": {\\n        \\"additional_properties\\": {\\n            \\"referenceCode\\": null,\\n            \\"messageFormat\\": null,\\n            \\"severity\\": null,\\n            \\"messageParameters\\": {}\\n        },\\n        \\"code\\": \\"UserError\\",\\n        \\"message\\": \\"User program failed with SystemExit: 2\\",\\n        \\"details_uri\\": \\"https://aka.ms/azureml-known-errors\\",\\n        \\"target\\": null,\\n        \\"details\\": [],\\n        \\"inner_error\\": null,\\n        \\"debug_info\\": {\\n            \\"additional_properties\\": {},\\n            \\"type\\": \\"SystemExit\\",\\n            \\"message\\": \\"2\\",\\n            \\"stack_trace\\": \\"  File \\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_1/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_1/azureml-setup/context_manager_injector.py\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\"__main__\\\\\\")\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\"train.py\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\"train.py\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \' \'.join(argv))\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2389, in error\\\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\\\\\n\') % args)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\",\\n            \\"inner_exception\\": null,\\n            \\"data\\": null,\\n            \\"error_response\\": null\\n        }\\n    },\\n    \\"correlation\\": null,\\n    \\"environment\\": null,\\n    \\"location\\": null,\\n    \\"time\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_2, {\'error\': {\\n    \\"additional_properties\\": {\\n        \\"componentName\\": null\\n    },\\n    \\"error\\": {\\n        \\"additional_properties\\": {\\n            \\"referenceCode\\": null,\\n            \\"messageFormat\\": null,\\n            \\"severity\\": null,\\n            \\"messageParameters\\": {}\\n        },\\n        \\"code\\": \\"UserError\\",\\n        \\"message\\": \\"User program failed with SystemExit: 2\\",\\n        \\"details_uri\\": \\"https://aka.ms/azureml-known-errors\\",\\n        \\"target\\": null,\\n        \\"details\\": [],\\n        \\"inner_error\\": null,\\n        \\"debug_info\\": {\\n            \\"additional_properties\\": {},\\n            \\"type\\": \\"SystemExit\\",\\n            \\"message\\": \\"2\\",\\n            \\"stack_trace\\": \\"  File \\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_2/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_2/azureml-setup/context_manager_injector.py\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\"__main__\\\\\\")\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\"train.py\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\"train.py\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \' \'.join(argv))\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2389, in error\\\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\\\\\n\') % args)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\",\\n            \\"inner_exception\\": null,\\n            \\"data\\": null,\\n            \\"error_response\\": null\\n        }\\n    },\\n    \\"correlation\\": null,\\n    \\"environment\\": null,\\n    \\"location\\": null,\\n    \\"time\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_3, {\'error\': {\\n    \\"additional_properties\\": {\\n        \\"componentName\\": null\\n    },\\n    \\"error\\": {\\n        \\"additional_properties\\": {\\n            \\"referenceCode\\": null,\\n            \\"messageFormat\\": null,\\n            \\"severity\\": null,\\n            \\"messageParameters\\": {}\\n        },\\n        \\"code\\": \\"UserError\\",\\n        \\"message\\": \\"User program failed with SystemExit: 2\\",\\n        \\"details_uri\\": \\"https://aka.ms/azureml-known-errors\\",\\n        \\"target\\": null,\\n        \\"details\\": [],\\n        \\"inner_error\\": null,\\n        \\"debug_info\\": {\\n            \\"additional_properties\\": {},\\n            \\"type\\": \\"SystemExit\\",\\n            \\"message\\": \\"2\\",\\n            \\"stack_trace\\": \\"  File \\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_3/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_3/azureml-setup/context_manager_injector.py\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\"__main__\\\\\\")\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\"train.py\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\"train.py\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \' \'.join(argv))\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2389, in error\\\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\\\\\n\') % args)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\",\\n            \\"inner_exception\\": null,\\n            \\"data\\": null,\\n            \\"error_response\\": null\\n        }\\n    },\\n    \\"correlation\\": null,\\n    \\"environment\\": null,\\n    \\"location\\": null,\\n    \\"time\\": {}\\n}}), (https://southcentralus.experiments.azureml.net/subscriptions/502bce8d-d66b-4661-a423-f21e61d20123/resourceGroups/aml-quickstarts-122756/providers/Microsoft.MachineLearningServices/workspaces/quick-starts-ws-122756/experiments/**SCRUBBED**/runs/HD_402d014f-07d3-4c64-b158-86d3d0890819_4, {\'error\': {\\n    \\"additional_properties\\": {\\n        \\"componentName\\": null\\n    },\\n    \\"error\\": {\\n        \\"additional_properties\\": {\\n            \\"referenceCode\\": null,\\n            \\"messageFormat\\": null,\\n            \\"severity\\": null,\\n            \\"messageParameters\\": {}\\n        },\\n        \\"code\\": \\"UserError\\",\\n        \\"message\\": \\"User program failed with SystemExit: 2\\",\\n        \\"details_uri\\": \\"https://aka.ms/azureml-known-errors\\",\\n        \\"target\\": null,\\n        \\"details\\": [],\\n        \\"inner_error\\": null,\\n        \\"debug_info\\": {\\n            \\"additional_properties\\": {},\\n            \\"type\\": \\"SystemExit\\",\\n            \\"message\\": \\"2\\",\\n            \\"stack_trace\\": \\"  File \\\\\\"/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-122756/azureml/hd_402d014f-07d3-4c64-b158-86d3d0890819_4/mounts/workspaceblobstore/azureml/HD_402d014f-07d3-4c64-b158-86d3d0890819_4/azureml-setup/context_manager_injector.py\\\\\\", line 181, in execute_with_context\\\\n    runpy.run_path(sys.argv[0], globals(), run_name=\\\\\\"__main__\\\\\\")\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 263, in run_path\\\\n    pkg_name=pkg_name, script_name=fname)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 96, in _run_module_code\\\\n    mod_name, mod_spec, pkg_name, script_name)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/runpy.py\\\\\\", line 85, in _run_code\\\\n    exec(code, run_globals)\\\\n  File \\\\\\"train.py\\\\\\", line 81, in <module>\\\\n    main()\\\\n  File \\\\\\"train.py\\\\\\", line 67, in main\\\\n    args = parser.parse_args()\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 1733, in parse_args\\\\n    self.error(msg % \' \'.join(argv))\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2389, in error\\\\n    self.exit(2, _(\'%(prog)s: error: %(message)s\\\\\\\\n\') % args)\\\\n  File \\\\\\"/opt/miniconda/lib/python3.6/argparse.py\\\\\\", line 2376, in exit\\\\n    _sys.exit(status)\\\\n\\",\\n            \\"inner_exception\\": null,\\n            \\"data\\": null,\\n            \\"error_response\\": null\\n        }\\n    },\\n    \\"correlation\\": null,\\n    \\"environment\\": null,\\n    \\"location\\": null,\\n    \\"time\\": {}\\n}})]",\n      "stackTrace": null,\n      "innerException": null,\n      "data": null,\n      "errorResponse": null\n    }\n  },\n  "correlation": null,\n  "environment": null,\n  "location": null,\n  "time": "0001-01-01T00:00:00+00:00",\n  "componentName": null\n}'}],
 'properties': {'primary_metric_config': '{"name": "Accuracy", "goal": "maximize"}',
  'resume_from': 'null',
  'runTemplate': 'HyperDrive',
  'azureml.runsource': 'hyperdrive',
  'platform': 'AML',
  'ContentSnapshotId': '921474d0-f2e1-4fc7-90e4-9c6e23e7adab'},
 'inputDatasets': [],
 'outputDatasets': [],
 'logFiles': {'azureml-logs/hyperdrive.txt': 'https://mlstrg122756.blob.core.windows.net/azureml/ExperimentRun/dcid.HD_402d014f-07d3-4c64-b158-86d3d0890819/azureml-logs/hyperdrive.txt?sv=2019-02-02&sr=b&sig=T1BtwIiemhufgagkEEbLFoZbXY1iUNqev0EDsT47aT4%3D&st=2020-10-25T05%3A12%3A36Z&se=2020-10-25T13%3A22%3A36Z&sp=r'}}